import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { PrimeReactProvider } from 'primereact/api';

import ReduxProvider from '@/components/providers/ReduxProvider';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import './globals.css';
import Script from 'next/script';
import Container from '@/components/common/Container';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Artidal',
    description: 'Generated by Artidal',
    manifest: '/manifest.json',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className='bg-white h-auto w-auto'>
            <body className={`${inter.className} h-full w-full`}>
                <Script id='register-service-worker'>
                    {`if ('serviceWorker' in navigator) {
              navigator.serviceWorker.register('./service-worker.js');
            } `}
                </Script>
                <PrimeReactProvider>
                    <ReduxProvider>
                        <Container>{children}</Container>
                    </ReduxProvider>
                </PrimeReactProvider>
            </body>
        </html>
    );
}
