export const en = {
  DASHBOARD: 'Dashboard',
  GUEST: 'Guest',
  BOOKING: 'booking',
  servicePLAN: 'Service Plan',
  serviceOPERATION: 'Service Operation',
  LEDGER: 'Ledger',
  SUPPLIER: 'Supplier',
  SUPPORT: 'Support',
  SETTINGS: 'Settings',
  ITEMS: 'Items',
  INSTRUCTOR: 'Instructor',
  SPOT: 'spot',
  digitalSIGNAGE: 'Digital Signage',
  USER: 'User',
  USERS: 'Users',
  USER_ADD: 'Add User',
  USERS_DESC: 'A list of all the users in your account including their name, mail, role and confirmend.',
  NAME: 'Name',
  MAIL: 'Mail',
  ROLE: 'Role',
  CONFIRMED: 'Confirmed',
  TAX: 'Tax',
  NOTIFFICATIONS: 'Notiffications',
};
