export const pt = {
  DASHBOARD: 'Painel',
  GUEST: 'Convidada',
  BOOKING: 'Reserva',
  servicePLAN: 'Plano de serviço',
  serviceOPERATION: 'Operação de serviço',
  LEDGER: 'Razão',
  SUPPLIER: 'Fornecedor',
  SUPPORT: 'Apoiar',
  SETTINGS: 'Configurações',
  ITEMS: 'Unid',
  INSTRUCTOR: 'Instrutor',
  SPOT: 'Ver',
  digitalSIGNAGE: 'Assinatura digital',
  USER: 'Do utilizador',
  USERS: 'Utilizadores',
  NAME: 'Nome',
  MAIL: 'Correio',
  ROLE: 'Papel',
  CONFIRMED: 'Confirmado',
  USER_ADD: 'Adicionar utilizador',
  USERS_DESC: 'Uma lista de todos os utilizadores da sua conta, incluindo o seu nome, e-mail, função e confirmação.',
  TAX: 'Imposto',
  NOTIFFICATIONS: 'Notificações',
};
